name: CI for Application Tests

on:
  pull_request:
    branches:
      - main # Adjust this to your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Specify the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code from your repository

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17" # Specify the version of Java
          distribution: "temurin" # Java distribution

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the application
        run: mvn clean package
        working-directory: movieRetirvalWebApp # Set the working directory to the movieRetrivalWebApp folder

      - name: Run the application tests
        run: mvn test
        working-directory: movieRetirvalWebApp # Set the working directory to the movieRetrivalWebApp folder
